# NUMPY

In [1]:
import numpy as np

In [1]:
# if addition 
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([1,2,3,4])

arr1+arr2

array([2, 4, 6, 8])

In [3]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [4]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a1,a2

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]))

In [5]:
# Scalar operations
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
# Scalar operations
a1*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [7]:
# Scalar operations
a1+2 # if scalar operation we multiply an array with a number

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [12]:
# relational
# it shows that each element is generate than is or not
a1>=15

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [10]:
# relational
# it shows that each element is generate than is or not
a1>=3

array([[False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [13]:
# vector operation
# if vector operation we perform any operation between them is vector 
arr1+arr2

array([2, 4, 6, 8])

In [14]:
# stacking
#Horizontal stacking
#vertical stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

np.hstack((a4,a5))
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [15]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

np.hstack((a4,a5))# 3*8 matrices

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [16]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

np.vstack((a4,a5)) # 6*4 matrices

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [17]:
# splitting
np.hsplit(a4,1)

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])]

In [18]:
# splitting
np.vsplit(a4,1)

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])]

In [19]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [20]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

np.vsplit(a5,1)

[array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [21]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

np.vsplit(a4,1)

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])]

In [22]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [23]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [25]:
#pandas (library)
# importing the module
import pandas as pd
my_dict = {"ather":[23,34,56,56],"zaid":[44,-4,0,-1],"talha":[17,55,27,21]}
pd.DataFrame(my_dict)

ather  zaid  talha
0     23    44     17
1     34    -4     55
2     56     0     27
3     56    -1     21

In [26]:
#creating a sample dataframe
data = pd.DataFrame({
          'Brand': ['Maruti', 'Hyundai', 'Tata',
                            'Mahindra', 'Maruti', 'Hyundai',
                            'Renault', 'Tata', 'Maruti'],
                    'Year': [2012, 2014, 2011, 2015, 2012,
                            2016, 2014, 2018, 2019],
                    'Kms Driven': [50000, 30000, 60000,
                                    25000, 10000, 46000,
                                    31000, 15000, 12000],
                    'City': ['Gurgaon', 'Delhi', 'Mumbai',
                            'Delhi', 'Mumbai', 'Delhi',
                            'Mumbai', 'Chennai', 'Ghaziabad'],
                    'Mileage': [28, 27, 25, 26, 28,
                                29, 24, 21, 24]})
#displaying the DataFrame

display(data)

Brand  Year  Kms Driven       City  Mileage
0    Maruti  2012       50000    Gurgaon       28
1   Hyundai  2014       30000      Delhi       27
2      Tata  2011       60000     Mumbai       25
3  Mahindra  2015       25000      Delhi       26
4    Maruti  2012       10000     Mumbai       28
5   Hyundai  2016       46000      Delhi       29
6   Renault  2014       31000     Mumbai       24
7      Tata  2018       15000    Chennai       21
8    Maruti  2019       12000  Ghaziabad       24

In [27]:
data["Year"]

0    2012
1    2014
2    2011
3    2015
4    2012
5    2016
6    2014
7    2018
8    2019
Name: Year, dtype: int64

In [28]:
data[['Year','Brand']]

Year     Brand
0  2012    Maruti
1  2014   Hyundai
2  2011      Tata
3  2015  Mahindra
4  2012    Maruti
5  2016   Hyundai
6  2014   Renault
7  2018      Tata
8  2019    Maruti

In [29]:
data['City']

0      Gurgaon
1        Delhi
2       Mumbai
3        Delhi
4       Mumbai
5        Delhi
6       Mumbai
7      Chennai
8    Ghaziabad
Name: City, dtype: object

In [30]:
data["Mileage"]

0    28
1    27
2    25
3    26
4    28
5    29
6    24
7    21
8    24
Name: Mileage, dtype: int64

In [31]:
#fetch row
data.iloc[4:8]

Brand  Year  Kms Driven     City  Mileage
4   Maruti  2012       10000   Mumbai       28
5  Hyundai  2016       46000    Delhi       29
6  Renault  2014       31000   Mumbai       24
7     Tata  2018       15000  Chennai       21

In [32]:
#fetch row
data.iloc[5:8]

Brand  Year  Kms Driven     City  Mileage
5  Hyundai  2016       46000    Delhi       29
6  Renault  2014       31000   Mumbai       24
7     Tata  2018       15000  Chennai       21

In [33]:
# fancy indexing
#data["kms driven","city"]
data.iloc[5:8,3:5]

City  Mileage
5    Delhi       29
6   Mumbai       24
7  Chennai       21

In [34]:
#data["brand","year"]
data.iloc[1:4,0:2]

Brand  Year
1   Hyundai  2014
2      Tata  2011
3  Mahindra  2015

In [35]:
data.iloc[0: ,0:]

Brand  Year  Kms Driven       City  Mileage
0    Maruti  2012       50000    Gurgaon       28
1   Hyundai  2014       30000      Delhi       27
2      Tata  2011       60000     Mumbai       25
3  Mahindra  2015       25000      Delhi       26
4    Maruti  2012       10000     Mumbai       28
5   Hyundai  2016       46000      Delhi       29
6   Renault  2014       31000     Mumbai       24
7      Tata  2018       15000    Chennai       21
8    Maruti  2019       12000  Ghaziabad       24

In [36]:
data.iloc[0::]

Brand  Year  Kms Driven       City  Mileage
0    Maruti  2012       50000    Gurgaon       28
1   Hyundai  2014       30000      Delhi       27
2      Tata  2011       60000     Mumbai       25
3  Mahindra  2015       25000      Delhi       26
4    Maruti  2012       10000     Mumbai       28
5   Hyundai  2016       46000      Delhi       29
6   Renault  2014       31000     Mumbai       24
7      Tata  2018       15000    Chennai       21
8    Maruti  2019       12000  Ghaziabad       24

In [37]:
data.iloc[4:8:3,3:5]


City  Mileage
4   Mumbai       28
7  Chennai       21

In [38]:
data.iloc[4:8:3,1:4:2]

Year     City
4  2012   Mumbai
7  2018  Chennai

In [39]:
data.iloc[2:4:1,1:3]

Year  Kms Driven
2  2011       60000
3  2015       25000

In [40]:
data.iloc[1:4:2,1:4:2]

Year   City
1  2014  Delhi
3  2015  Delhi

In [41]:
data.iloc[1:5:3]

Brand  Year  Kms Driven    City  Mileage
1  Hyundai  2014       30000   Delhi       27
4   Maruti  2012       10000  Mumbai       28

In [42]:
data.iloc[[1,2,4]]

Brand  Year  Kms Driven    City  Mileage
1  Hyundai  2014       30000   Delhi       27
2     Tata  2011       60000  Mumbai       25
4   Maruti  2012       10000  Mumbai       28

In [43]:
data.iloc[[2,3,5],[2,4]]

Kms Driven  Mileage
2       60000       25
3       25000       26
5       46000       29

In [44]:
#fetch function
#rows 0,5,7,9 and first{last column}
data.iloc[[0,5,7,8],[0,4]]

Brand  Mileage
0   Maruti       28
5  Hyundai       29
7     Tata       21
8   Maruti       24

In [45]:
data.iloc[[0,5,7,8],0:5]

Brand  Year  Kms Driven       City  Mileage
0   Maruti  2012       50000    Gurgaon       28
5  Hyundai  2016       46000      Delhi       29
7     Tata  2018       15000    Chennai       21
8   Maruti  2019       12000  Ghaziabad       24

In [46]:
data.iloc[0:9,[4]]

Mileage
0       28
1       27
2       25
3       26
4       28
5       29
6       24
7       21
8       24

In [47]:
data.iloc[0:4]

Brand  Year  Kms Driven     City  Mileage
0    Maruti  2012       50000  Gurgaon       28
1   Hyundai  2014       30000    Delhi       27
2      Tata  2011       60000   Mumbai       25
3  Mahindra  2015       25000    Delhi       26

In [48]:
data.loc[0:4]

Brand  Year  Kms Driven     City  Mileage
0    Maruti  2012       50000  Gurgaon       28
1   Hyundai  2014       30000    Delhi       27
2      Tata  2011       60000   Mumbai       25
3  Mahindra  2015       25000    Delhi       26
4    Maruti  2012       10000   Mumbai       28

In [49]:
data.loc[0:3]

Brand  Year  Kms Driven     City  Mileage
0    Maruti  2012       50000  Gurgaon       28
1   Hyundai  2014       30000    Delhi       27
2      Tata  2011       60000   Mumbai       25
3  Mahindra  2015       25000    Delhi       26

In [50]:
data.iloc[[0,5]]

Brand  Year  Kms Driven     City  Mileage
0   Maruti  2012       50000  Gurgaon       28
5  Hyundai  2016       46000    Delhi       29

In [51]:
#selecting rows from 1 to 4 and columns
data.iloc[[2,6],3:5]

City  Mileage
2  Mumbai       25
6  Mumbai       24

In [52]:
data.iloc[0:7,3:5]

City  Mileage
0  Gurgaon       28
1    Delhi       27
2   Mumbai       25
3    Delhi       26
4   Mumbai       28
5    Delhi       29
6   Mumbai       24

In [53]:
data.iloc[0:5:2,[0,1,4]]

Brand  Year  Mileage
0  Maruti  2012       28
2    Tata  2011       25
4  Maruti  2012       28

In [54]:
data.iloc[[1,6,8]]

Brand  Year  Kms Driven       City  Mileage
1  Hyundai  2014       30000      Delhi       27
6  Renault  2014       31000     Mumbai       24
8   Maruti  2019       12000  Ghaziabad       24

In [55]:
data.iloc[7:9,3:5]

City  Mileage
7    Chennai       21
8  Ghaziabad       24

In [56]:
data.iloc[[0,3,7],0::2]

Brand  Kms Driven  Mileage
0    Maruti       50000       28
3  Mahindra       25000       26
7      Tata       15000       21

In [57]:
data.Year==2014

0    False
1     True
2    False
3    False
4    False
5    False
6     True
7    False
8    False
Name: Year, dtype: bool

In [58]:
data.loc[data.Year==2014]

Brand  Year  Kms Driven    City  Mileage
1  Hyundai  2014       30000   Delhi       27
6  Renault  2014       31000  Mumbai       24

In [59]:
data.loc[data.Mileage>25]

Brand  Year  Kms Driven     City  Mileage
0    Maruti  2012       50000  Gurgaon       28
1   Hyundai  2014       30000    Delhi       27
3  Mahindra  2015       25000    Delhi       26
4    Maruti  2012       10000   Mumbai       28
5   Hyundai  2016       46000    Delhi       29

In [60]:
data.loc[data["Kms Driven"]>10000]

Brand  Year  Kms Driven       City  Mileage
0    Maruti  2012       50000    Gurgaon       28
1   Hyundai  2014       30000      Delhi       27
2      Tata  2011       60000     Mumbai       25
3  Mahindra  2015       25000      Delhi       26
5   Hyundai  2016       46000      Delhi       29
6   Renault  2014       31000     Mumbai       24
7      Tata  2018       15000    Chennai       21
8    Maruti  2019       12000  Ghaziabad       24

In [61]:
data.loc[(data.Brand =="Maruti")&(data.Mileage==28)]

Brand  Year  Kms Driven     City  Mileage
0  Maruti  2012       50000  Gurgaon       28
4  Maruti  2012       10000   Mumbai       28

In [62]:
data.loc[(data.Brand =="Maruti")&(data.Mileage>25)]

Brand  Year  Kms Driven     City  Mileage
0  Maruti  2012       50000  Gurgaon       28
4  Maruti  2012       10000   Mumbai       28

In [63]:
data.loc[(data["Kms Driven"]>10000)&(data.Mileage>25)]

Brand  Year  Kms Driven     City  Mileage
0    Maruti  2012       50000  Gurgaon       28
1   Hyundai  2014       30000    Delhi       27
3  Mahindra  2015       25000    Delhi       26
5   Hyundai  2016       46000    Delhi       29

In [64]:
#kms driven<3000, brand (tata), city(Mumbai)
# kms driven less than equal to 3000 and city Mumbai & brand tata ya hundai
data.loc[(data["Kms Driven"]<=3000)&(data.City=="Mumbai")&((data.Brand=="Tata")|(data.Brand=="Hundai"))]

Empty DataFrame
Columns: [Brand, Year, Kms Driven, City, Mileage]
Index: []

In [65]:
data.loc[((data.Brand=="Tata")|(data.Brand=="Hyundai"))&(data.Year>2014)]

Brand  Year  Kms Driven     City  Mileage
5  Hyundai  2016       46000    Delhi       29
7     Tata  2018       15000  Chennai       21

In [66]:
#kms less than 30000,city Mumbai or Chennai , Mileage 25|28
data.loc[((data["Kms Driven"]<30000)&(data.City=="Mumbai")|(data.City=="Chennai")&((data.Mileage==25)|(data.Mileage==28)))]

Brand  Year  Kms Driven    City  Mileage
4  Maruti  2012       10000  Mumbai       28

In [67]:
My_dict={
    "Girls":["Waleed","Mahrukh","Hamna","Ayesha","Aiman","Anabia"],
     "Intelligence": [60,10,20,30,40,50],
     "IQ":[70,50,60,70,80,90]
                            }
pd.DataFrame(My_dict)

Girls  Intelligence  IQ
0   Waleed            60  70
1  Mahrukh            10  50
2    Hamna            20  60
3   Ayesha            30  70
4    Aiman            40  80
5   Anabia            50  90

In [2]:
import numpy as np
a1=np.arange(10,dtype=np.int32)
a2=np.arange(12,dtype=np.float32).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)

In [2]:
import numpy as np
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
# The arange function is used to generate a range of values, similar to Python's built-in range function
#This line creates an array containing odd integers from 1 to 10. The third argument, 2, specifies the step size
import numpy as np
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [4]:
#3D
np.arange(16).reshape(2,2,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [5]:
np.arange(1,12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [7]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
#give you any random values
np.random.random((3,4))

array([[0.87803431, 0.03540616, 0.52297873, 0.12819154],
       [0.09797527, 0.07409076, 0.970927  , 0.92003948],
       [0.41043347, 0.1279117 , 0.42897127, 0.14092402]])

In [10]:
#uses NumPy's linspace function to create an array of 11 evenly spaced integers
##linspace gives you equall amount of space between numbers
np.linspace(-30,30,12,dtype=int)

array([-30, -25, -20, -14,  -9,  -3,   2,   8,  13,  19,  24,  30])

In [11]:
#14: The number of elements in the sequence, including the start and end values
np.linspace(-40,40,14,dtype=int)

array([-40, -34, -28, -22, -16, -10,  -4,   3,   9,  15,  21,  27,  33,
        40])

In [12]:
np.identity((4))

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
#ODD NUMBERS
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [22]:
np.array([[1, 3, 5, 7, 9],[9, 15, 21, 27, 33]])

array([[ 1,  3,  5,  7,  9],
       [ 9, 15, 21, 27, 33]])

In [24]:
np.array([[1, 3, 5, 7, 9],[9, 15, 21, 27, 33]],dtype=float)

array([[ 1.,  3.,  5.,  7.,  9.],
       [ 9., 15., 21., 27., 33.]])

In [3]:
a1=np.arange(10,dtype=np.int32)
a2=np.arange(12,dtype=np.float64).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# ATTRIBUTES

In [30]:
#tells the dimension of array
a3.ndim

3

In [32]:
#shape
a2.shape

(3, 4)

In [34]:
#TOTAL NUM OF ITEms in array(SIZE)
a1.size

10

In [35]:
a2.dtype

dtype('float64')

In [37]:
#how much bytes the item occupy in the memory
a3.itemsize

4

In [38]:
# converting the array a3 to a new array with the data type
a3.astype(np.int64)
a3.itemsize

4

In [39]:
a1.astype(np.int64)
a1.itemsize

4

In [8]:
a2[1,2]

6.0

In [9]:
a2[1,3]

7.0

In [14]:
a3[1,0,0]
a3[0,1,1]

3

# SLICING

In [17]:
a1[2:7]
#[start:step:jump]
a1[5:9:3]

array([5, 8])

In [25]:
a2[1,1:3]

array([5., 6.])

In [29]:
a2[0:2,1:3]

array([[1., 2.],
       [5., 6.]])

In [32]:
a2[0,1:]

array([1., 2., 3.])

In [34]:
a3[1,1:]

array([[6, 7]])

In [35]:
a3=np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [41]:
a3[2,:,2]
a3[2,:,1]
a3[1,:,1]

array([10, 13, 16])

In [42]:
for i in (a3):
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [44]:
#np.nditer function to iterate over the elements of the array a3
for i in np.nditer(a1):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [47]:
a4=np.random.random((3,3))
a4
np.round(a4*100)

array([[ 3., 39., 87.],
       [81., 25., 15.],
       [24.,  6., 33.]])

In [48]:
#sum
#axis 0--row
#axis 1--col
np.sum(a3,axis =0)

array([[27, 30, 33],
       [36, 39, 42],
       [45, 48, 51]])

In [49]:
np.sum(a3,axis=1)

array([[ 9, 12, 15],
       [36, 39, 42],
       [63, 66, 69]])

In [51]:
np.max(a3)
np.max(a3,axis=1)

array([[ 6,  7,  8],
       [15, 16, 17],
       [24, 25, 26]])

In [54]:
np.mean(a3)
# np.mode(a3)
# np.median(a3)

13.0

In [55]:
np.median(a3)

13.0

In [56]:
np.floor(a3)
np.ceil(a3)
np.round(a3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [57]:
#scalar opreations
import numpy as np
a1=np.arange(10,dtype=np.int32)
a2=np.arange(12,dtype=np.float32).reshape(3,4)
a3=np.arange(27).reshape(3,3,3)
a1+2
a1*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [58]:
#vector (any opreation between array )
# relational
a1>15

array([False, False, False, False, False, False, False, False, False,
       False])

In [59]:
#stacking
a4=np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
np.hstack((a4,a5))
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [60]:
a4=np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
np.hstack((a4,a5)) #side by side

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [63]:
#dot product--1 matrix ky rown = 2nd ky number of coloumns
#spliting
a4=np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
np.hsplit(a4 ,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [64]:
a4=np.arange(16).reshape(4,4)
np.vsplit(a4 ,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [65]:
import numpy as np
a6=np.arange(20).reshape(5,4)
a6

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])